some changes
MarkiyanSHCH/Ecommercial pull request #4
Opened 2021-10-07 11:37 UTC by MarkiyanSHCH

2021-10-07 12:05 UTC, BodyDuk commented on WebAPI/AuthApi/Controllers/AuthController.cs
> +            var user = _authServices.GetUser(_configuration, request);
Specify the type.

2021-10-07 12:06 UTC, BodyDuk commented on WebAPI/AuthApi/Controllers/AuthController.cs
> +                var token = _authServices.GenerateJWT(user);
Specify the type.

2021-10-07 12:06 UTC, BodyDuk commented on WebAPI/AuthApi/Controllers/AuthController.cs
>              }
Put this code in one line.

2021-10-07 12:07 UTC, BodyDuk commented on WebAPI/AuthApi/Repository/AuthRepository.cs
> +
Redundant lines.

2021-10-07 12:08 UTC, BodyDuk commented on WebAPI/AuthApi/Repository/AuthRepository.cs
> +            string sqlDataSource = _configuration.GetConnectionString("ProductAppCon");
Take the connection string to the constructor.

2021-10-07 12:09 UTC, BodyDuk commented on WebAPI/AuthApi/Services/AuthServices.cs
> +            _authRepository = new AuthRepository();
Use Dependency Injection.

2021-10-07 12:09 UTC, BodyDuk commented on WebAPI/WebAPI/Controllers/CategoryController.cs
> +            _categoryServices = new CategoryServices();
Use Dependency Injection.

2021-10-07 12:09 UTC, BodyDuk commented on WebAPI/WebAPI/Controllers/OrdersController.cs
> +            _orderServices = new OrderServices();
Use Dependency Injection.

2021-10-07 12:11 UTC, BodyDuk commented on WebAPI/WebAPI/obj/project.nuget.cache
>  }
Remove this file from the commit.

2021-10-07 12:11 UTC, BodyDuk commented on WebAPI/WebAPI/obj/WebAPI.csproj.nuget.g.props
>  </Project>
Remove this file from the commit.

2021-10-07 12:11 UTC, BodyDuk commented on WebAPI/WebAPI/obj/WebAPI.csproj.nuget.dgspec.json
>              "System.Data.SqlClient": {
Remove this file from the commit.

2021-10-07 12:11 UTC, BodyDuk commented on WebAPI/AuthCommon/obj/project.assets.json
>        "System.IdentityModel.Tokens.Jwt >= 6.12.2"
Remove this file from the commit.

2021-10-07 12:12 UTC, BodyDuk commented on WebAPI/AuthCommon/obj/AuthCommon.csproj.nuget.dgspec.json
>          "netcoreapp3.1": {
Remove this file from the commit.

2021-10-07 12:12 UTC, BodyDuk commented on WebAPI/AuthApi/obj/project.nuget.cache
>      "C:\\Users\\Macbook\\.nuget\\packages\\runtime.win-arm64.runtime.native.system.data.sqlclient.sni\\4.4.0\\runtime.win-arm64.runtime.native.system.data.sqlclient.sni.4.4.0.nupkg.sha512",
Remove this file from the commit.

2021-10-07 12:12 UTC, BodyDuk commented on WebAPI/AuthApi/obj/project.assets.json
> +        "microsoft.csharp.4.5.0.nupkg.sha512",
Remove this file from the commit.

2021-10-07 12:12 UTC, BodyDuk commented on WebAPI/AuthApi/obj/AuthApi.csproj.nuget.dgspec.json
>              "System.Data.SqlClient": {
Remove this file from the commit.

2021-10-07 12:13 UTC, BodyDuk commented on WebAPI/WebAPI/Controllers/ProductController.cs
Redundant lines.

2021-10-07 12:13 UTC, BodyDuk commented on WebAPI/WebAPI/Controllers/CategoryController.cs
Redundant lines.

2021-10-07 12:14 UTC, BodyDuk commented on WebAPI/AuthCommon/obj/project.nuget.cache
> +  "dgSpecHash": "oo+MRW75SCK0E0yjsfvXbKh8rzyLWI5EDlT+aZQ1l1exwY7pxU3p9cMlyzecetKIqdOk0TUGydMlRahKF57pUA==",
Remove this file from the commit.

2021-10-07 12:14 UTC, BodyDuk commented on WebAPI/AuthApi/obj/project.assets.json
>          "targetAlias": "netcoreapp3.1",
Remove this file from the commit.

2021-10-07 12:16 UTC, BodyDuk commented on WebAPI/AuthApi/Controllers/AuthController.cs
>      public class AuthController : ControllerBase
Specify access rights to the controller.

2021-10-07 12:23 UTC, BodyDuk commented on WebAPI/AuthApi/Repository/AuthRepository.cs
> +                myCon.Close();
There is no need to close conventions.

2021-10-07 12:23 UTC, BodyDuk commented on WebAPI/AuthApi/Repository/AuthRepository.cs
> +
Redundant line.

2021-10-07 12:24 UTC, BodyDuk commented on WebAPI/AuthApi/Repository/AuthRepository.cs
> +            var account = new Account();
You need to create this object.

2021-10-07 12:25 UTC, BodyDuk commented on WebAPI/AuthApi/Repository/AuthRepository.cs
> +                myCon.Open();
Use more meaningful variable names.

2021-10-07 12:26 UTC, BodyDuk commented on WebAPI/AuthApi/Repository/AuthRepository.cs
> +                command.Parameters.Add("@pPassword", SqlDbType.NVarChar, 100).Value = request.Password;
Why did you add p before parameter names?

2021-10-07 12:26 UTC, BodyDuk commented on WebAPI/AuthApi/Repository/AuthRepository.cs
> +            using (SqlCommand command = new SqlCommand("spUsers_GetUser", myCon))
Where can I see the code for this procedure?

2021-10-07 12:28 UTC, BodyDuk commented on WebAPI/WebAPI/Controllers/OrdersController.cs
>          public IActionResult GetOrders()
You do not need this line.

2021-10-07 12:28 UTC, BodyDuk commented on WebAPI/WebAPI/Controllers/ProductController.cs
> +            return Ok(_productServices.GetById(_configuration, id));
Cover negative flows.

2021-10-07 12:40 UTC, MarkiyanSHCH commented on WebAPI/AuthApi/Controllers/AuthController.cs
> +                var token = _authServices.GenerateJWT(user);
+

2021-10-07 12:40 UTC, MarkiyanSHCH commented on WebAPI/AuthApi/Controllers/AuthController.cs
>              }
+

2021-10-11 10:00 UTC, BodyDuk commented on UI/angular/src/app/components/orders/orders.component.html
> +<table class="table">
use col

2021-10-11 10:02 UTC, BodyDuk commented on UI/angular/src/app/components/orders/orders.component.ts
>        .subscribe(res =>{
You don't need breakers.

2021-10-11 10:06 UTC, BodyDuk commented on UI/angular/src/app/components/products/detail/detail.component.html
> +</div>
Check all css classes.

2021-10-11 10:17 UTC, BodyDuk commented on UI/angular/src/app/components/products/products.component.html
> +<div class="container" style="margin-top:50px;">
Style

2021-10-11 10:17 UTC, BodyDuk commented on UI/angular/src/app/components/products/products.component.html
> +  <div class="row ">
space

2021-10-11 10:18 UTC, BodyDuk commented on UI/angular/src/app/components/products/products.component.html
> +    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3"
xs

2021-10-11 10:18 UTC, BodyDuk commented on UI/angular/src/app/components/products/products.component.html
> +      </div><br>
br

2021-10-11 10:46 UTC, BodyDuk commented on WebAPI/WebAPI/Startup.cs
>              var authOptions = Configuration.GetSection("Auth").Get<AuthOptions>();
Why do you need this?

2021-10-11 10:47 UTC, BodyDuk commented on WebAPI/WebAPI/Services/ProductServices.cs
>              string queryChar = @"Exec ReadCharacteristicForProduct @idProduct = " + id;
Use SP.

2021-10-12 14:38 UTC, BodyDuk requested changes

2021-10-12 14:38 UTC, BodyDuk commented on WebAPI/Core/Repository/IProductRepository.cs
> +        public IEnumerable<Product> GetAll();
You don`t need public.

2021-10-12 14:38 UTC, BodyDuk commented on WebAPI/Core/Services/AuthServices.cs
> +            => _authRepository.GetAccount(Email, Password);
Add this.

2021-10-12 14:38 UTC, BodyDuk commented on WebAPI/Core/Services/AuthServices.cs
> +            var authParams = _authOptions.Value;
Specify type and add this.

2021-10-12 14:38 UTC, BodyDuk commented on WebAPI/Data/Programmability/Stored Procedures/ReadAllCategories.sql
> +ALTER PROCEDURE [dbo].[ReadAllCategories]
Fix SP

2021-10-12 14:38 UTC, BodyDuk commented on WebAPI/Data/Programmability/Stored Procedures/ReadAllProducts.sql
> +ALTER PROCEDURE [dbo].[ReadAllProducts]
Fix

2021-10-12 14:38 UTC, BodyDuk commented on WebAPI/WebAPI/Models/Login.cs
> +
fix

2021-10-13 07:22 UTC, bdemediuk commented on WebAPI/Data/Models/ProductDTO.cs
> +                 Id = !reader.IsDBNull(reader.GetOrdinal("Id"))
If the value is not notable you don't need this check.

2021-10-13 07:24 UTC, bdemediuk commented on WebAPI/Data/Programmability/Stored Procedures/ReadAllProducts.sql
> +	Products.[Name],
Fix!

2021-10-13 07:24 UTC, bdemediuk commented on WebAPI/Data/Programmability/Stored Procedures/ReadCharacteristicForProduct.sql
> +CREATE PROCEDURE [dbo].[ReadCharacteristicForProduct] @idProduct INT
New line.

2021-10-13 07:26 UTC, bdemediuk commented on WebAPI/Data/Programmability/Stored Procedures/ReadCharacteristicForProduct.sql
> +    CategoryCharacterictic
Format the code.

2021-10-13 07:26 UTC, bdemediuk commented on WebAPI/Data/Programmability/Stored Procedures/ReadProductsByCategory.sql
> +	Products.[Name],
Fix!

2021-10-13 07:27 UTC, bdemediuk commented on WebAPI/Data/Programmability/Stored Procedures/ReadProductsById.sql
> +SELECT * FROM Products
Specify parameters.

2021-10-13 07:29 UTC, bdemediuk commented on WebAPI/Data/Programmability/Stored Procedures/spProduct_GetOrdersProduct.sql
> +SELECT p.* FROM Products p, Orders o,Users u
FIX

2021-10-13 07:30 UTC, bdemediuk commented on WebAPI/Data/Programmability/Stored Procedures/spProduct_GetProductByIdWithCharacteristic.sql
>  INNER JOIN CategoryCharacterictic AS cc
Use more meaningful names.

2021-10-18 07:29 UTC, bdemediuk requested changes

2021-10-18 07:29 UTC, bdemediuk commented on UI/angular/src/app/components/products/products.component.css
>      font-weight: bold;
font-weight-bold

2021-10-18 07:29 UTC, bdemediuk commented on UI/angular/src/app/components/products/products.component.html
> +    <div class="col-sm-6 col-md-4 col-lg-3"
Use col-6 instead of col-sm-6

2021-10-18 07:29 UTC, bdemediuk commented on UI/angular/src/app/module/authorization-dashboard/authorization-dashboard.module.ts
> +
Redundant space.

2021-10-18 07:29 UTC, bdemediuk commented on UI/angular/src/app/module/authorization-dashboard/login-dashboard/login-dashboard.component.css
> +    width: 100%;
Use w-100

2021-10-18 07:29 UTC, bdemediuk commented on UI/angular/src/app/module/authorization-dashboard/login-dashboard/login-dashboard.component.html
> +        <button class ="btn" type="button" aria-label="Close" (click)="activeModal.dismiss()">
Add enters.

2021-10-18 07:29 UTC, bdemediuk commented on UI/angular/src/app/module/authorization-dashboard/login-dashboard/login-dashboard.component.html
> +
Redundant spaces.

2021-10-18 07:29 UTC, bdemediuk commented on UI/angular/src/app/services/category.service.ts
> +  constructor(private http: HttpClient, @Inject(API_URL) private apiUrl: string) { }
Add _ to private var.

2021-10-18 07:29 UTC, bdemediuk commented on WebAPI/Core/Services/AuthServices.cs
> +            if(user != null)
Merge if.

2021-10-18 12:46 UTC, bdemediuk commented on UI/angular/src/app/app.component.html
> +            <form
You don't need this.

2021-10-18 12:47 UTC, bdemediuk commented on UI/angular/src/app/components/products/detail/detail.component.html
>  <div class="container mt-5 mb-5">
You can use `my-5`

2021-10-18 12:48 UTC, bdemediuk commented on UI/angular/src/app/components/products/detail/detail.component.html
> +          *ngIf="Product">
Use lower case.

2021-10-18 12:50 UTC, bdemediuk commented on UI/angular/src/app/components/products/detail/detail.component.html
> +                <li>{{char.name}}: {{char.value}}</li>
Use better naming.

2021-10-18 12:54 UTC, bdemediuk commented on UI/angular/src/app/services/order.service.ts
> +  private baseApiUrl = `${this._apiUrl}api/`
Use _

2021-10-18 12:57 UTC, bdemediuk commented on WebAPI/Core/Services/AuthServices.cs
> +            if (user != null || user.Password == Password)
Use ? :

2021-10-18 14:13 UTC, bdemediuk commented on WebAPI/Core/Services/AuthServices.cs
> +            return user != null || user.Password == Password ? user : null;
Fix!

2021-10-18 14:19 UTC, bdemediuk commented on UI/angular/src/app/module/authorization-dashboard/login-dashboard/login-dashboard.component.ts
> +  ngOnInit(): void {
Delet it

2021-10-18 14:21 UTC, bdemediuk commented on UI/angular/src/app/module/authorization-dashboard/login-dashboard/login-dashboard.component.ts
> +    this.login.next(this.model);
call this method in html.

2021-10-18 14:22 UTC, bdemediuk commented on UI/angular/src/app/module/authorization-dashboard/login-dashboard/login-dashboard.component.ts
> +  errorMessage(err: string): void {
call this method in html.

2021-10-18 14:24 UTC, bdemediuk commented on UI/angular/src/app/services/product.service.ts
> +    ) { }
f

2021-10-18 14:24 UTC, bdemediuk commented on UI/angular/src/polyfills.ts
> +import '@angular/localize/init';
?

2021-10-18 14:38 UTC, bdemediuk commented on WebAPI/Data/Repository/ProductRepository.cs
> +            => (this._sqlDataSource) = (configuration.GetConnectionString("ProductAppCon"));
( Y ) -

2021-10-18 14:41 UTC, bdemediuk commented on WebAPI/WebAPI/Controllers/CategoryController.cs
> +        public readonly CategoryServices _categoryServices;
private

2021-10-19 08:00 UTC, merged