Add hashing password
MarkiyanSHCH/Ecommercial pull request #6
Opened 2021-11-01 13:59 UTC by MarkiyanSHCH

In back-end create service for hashing like in FS, add to authController new HttpPost request (Registration) also add new SP (spUsers_AddUser).
In front-end create modal for registration and Registration model.

2021-11-04 15:18 UTC, bdemediuk requested changes

2021-11-04 15:18 UTC, bdemediuk commented on WebAPI/Core/Services/AuthServices.cs
> +            => (this._authOptions, this._authRepository, this._hashingService) = (authOptions, authRepository, hashingService);
Use usual indentation instep of an arrow function when you have more than 2 parameters.

2021-11-04 16:16 UTC, bdemediuk requested changes

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/Core/Services/Hashing/HashingService.cs
> +            this._hashFormatter = new HashFormatter();
this._hashFormatter = new HashFormatter();

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/Core/Services/Hashing/HashingService.cs
> +                ParametersPolicy policy = this._supportedPolicies.GetValueOrDefault(this._settings.HashAlgorithmName);
Why do you need this?

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/Core/Services/Hashing/HashingService.cs
> +                if (policy == null) return null;
Use the seme formate for this

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/Core/Services/Hashing/HashingService.cs
> +                    password: input,
Why do you need pass named params?

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/Core/Services/Hashing/HashingService.cs
> +            catch (Exception ex)
Why do you need ex?

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/Core/Services/Hashing/HashingService.cs
> +        public bool Check(string hash, string input)
Add validation

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/Core/Services/Hashing/HashingService.cs
> +                bool verified = inputKey.SequenceEqual(hashedKey);
Why do you need `verified`?

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/Data/Programmability/Stored Procedures/spUsers_AddUser.sql
> +    WHERE [ROUTINE_NAME] = 'spUsers_AddUser'
`spUsers_Add`

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/WebAPI/Models/PostRegistrationAccountRequest.cs
> +        public string Password { get; set; }
Add validation

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/WebAPI/Startup.cs
> +            var authOptions = _configuration.GetSection("Auth").Get<AuthOptions>();
Add this

2021-11-04 16:16 UTC, bdemediuk commented on WebAPI/WebAPI/Startup.cs
> +            services.Configure<AuthOptions>(_configuration.GetSection("Auth"));
Add this

2021-11-05 09:31 UTC, bdemediuk requested changes

2021-11-05 09:31 UTC, bdemediuk commented on WebAPI/Core/Services/Hashing/HashingService.cs
> +                    throw new ArgumentNullException();
ArgumentException

2021-11-05 09:31 UTC, bdemediuk commented on WebAPI/WebAPI/Models/PostRegistrationAccountRequest.cs
>          [Required]
More validation

2021-11-05 09:59 UTC, BodyDuk approved these changes

2021-11-05 11:33 UTC, merged