Feature/order page
MarkiyanSHCH/Ecommercial pull request #7
Opened 2021-11-08 15:07 UTC by MarkiyanSHCH

2021-11-08 15:35 UTC, BodyDuk requested changes

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/cart/cart.component.html
> +<div class="container pt-5 pt-md-6 pb-5">
py-5

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/cart/cart.component.html
> +      data-seel-text="page-header">Shopping Bag ({{cartItems.length}})</h3>
data-seel-text="page-header"???????

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/cart/cart.component.html
> +  <div *ngIf="cartItems.length === 0">
Why do you need this div?

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/cart/cart.component.html
> +                class="btn btn-outline-dark my-2 px-4 py-2">Continue Browsing</button>
Why do you need mb?

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/orders/order-collapse/order-collapse.component.html
> +  <div id="{{order.id}}"
In a row, must be only col.

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/orders/order-line/order-line.component.css
> +  max-width: 100%;
If you reuse this style, make it global.

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/orders/orders.component.ts
> +        .subscribe(res => this.shops = res.shops),
Redundant coma.

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/orders/orders.component.ts
>      forkJoin({
Pleas fix forkJoin

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/orders/orders.component.ts
>    }
Use better naming.

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/orders/orders.component.ts
> +    if (!this.orderLinesMap.get(orderId))
Try to add spinner.

2021-11-08 15:35 UTC, BodyDuk commented on UI/angular/src/app/components/products/detail/detail.component.ts
> +    console.log(this.product)
Delete console.log(this.product)

2021-11-09 08:46 UTC, bdemediuk requested changes

2021-11-09 08:46 UTC, bdemediuk commented on UI/angular/src/app/components/cart/cart.component.html
> +  <h3 class="mb-4">Shopping Bag ({{cartItems.length}})</h3>
Use mt

2021-11-09 08:46 UTC, bdemediuk commented on UI/angular/src/app/components/cart/cart.component.html
> +          <span>${{dataItem.quantity*getProductByProductId(dataItem.productId).price}}</span>
Add spaces.

2021-11-09 08:46 UTC, bdemediuk commented on UI/angular/src/app/components/cart/cart.component.html
> +      <h5 class="mb-6 text-transform-none">Your shopping bag is empty.</h5>
Why do you need `text-transform-none`

2021-11-09 08:46 UTC, bdemediuk commented on UI/angular/src/app/components/cart/cart.component.html
> +      <h5 class="mb-6 text-transform-none">Your shopping bag is empty.</h5>
Use mt

2021-11-09 08:46 UTC, bdemediuk commented on UI/angular/src/app/components/orders/order-collapse/order-collapse.component.html
> +<div id="{{order.id}}"
Why you use id="{{order.id}}"?

2021-11-09 09:35 UTC, bdemediuk approved these changes

2021-11-09 09:42 UTC, merged